### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by levinsonmm** [levinsonmm/MI-449-SS17-741-css-frameworks-p1twXJ#1]
@KatieMFritz Can you take a look at this? It's [hosted here](https://levinsonmm.github.io/MI-449-SS17-741-css-frameworks-p1twXJ/) and meets the following criteria:

- [x] Include the CSS and JS for Bootstrap 3 (not 4) in the page (including the "jQuery" dependency)
- [x] Use the `container` class to center your page content
- [x] Use a `navbar` class to display the name of your site and a list of at least 3 links (to past projects, or anything else) at the top of your page
- [x] Split your main content into 2 columns on large (`lg`) and medium (`md`) sized screens, but collapse them on top of each other on small (`sm`) and extra small (`xs`) screens
- [x] Use a `thumbnail` class on an at least one image in your page

For some reason the link to my hosted site isn't working for me. Also I'm really not sure if I did the container class or columns right, so I'm looking for some feedback!

**Comment by levinsonmm** [comment]
(Hosted site works now)

**Comment by KatieMFritz** [comment]
> Madeline Inc. offers two services: rainbows and clouds.

🌈 ☁️ 😂 

### Bootstrap grid system

>Also I'm really not sure if I did the container class or columns right, so I'm looking for some feedback!

You're close, but not quite there with the grid system. Check out [the first answer here](http://stackoverflow.com/questions/19983857/when-should-i-use-container-and-row-in-twitter-bootstrap-3) for a good example of how to use the `container` and `row` classes. [This example in the Boostrap docs](http://getbootstrap.com/css/#grid-example-basic) shows how to use `col` classes the way we want you to use them for this project.

If you're still confused after looking at those resources, don't worry. Reach out to me on Slack (direct message me @katiemfritz) or in class tomorrow and we can work on this together. 😄 It can take some time to get used to it.

Your navbar also looks a little different than I expected, though not bad! Can you show me the link where you got that code from? ❔ ❔ 
* * *
### Extra JavaScript?
Great job including jQuery and Bootstrap JS in the correct location on the page! 🎉 

I notice you are also including a library called Tether. What's Tether for? Where did you find the instructions to use it? I haven't heard of it.

If you don't know why you're using it either, I'd get rid of it - it's not causing any console errors, but it still could be interfering with other things on your site. 😮 
* * *
### Indentation and Spacing

Your spacing is pretty good overall, but I notice there's an extra line at the beginning of your document. I can't think of a situation where you'd ever want/need that. 🙂 

Your indentation all makes sense! Make sure as you move things around with your edits that you also double check indentation. It's very easy to get messy when you're working with all the nested `div`s in Bootstrap. 
* * *
After you’ve made your changes and pushed them to GitHub and your hosted site, give it a once-over to make sure it looks right, then comment back here and I’ll take another look. Or Slack me if you have questions along they way!

Thanks! :rocket:

**Comment by levinsonmm** [comment]
Alright I changed some things. If you could take a look and let me know how it is now, that'd be great!

I'm not sure what tether is either, I must have just copied it from wherever i got bootstrap from.

I got the navbar code by tweaking some examples that were given on the bootstrap documentation for navbars https://v4-alpha.getbootstrap.com/components/navbar/

**Comment by KatieMFritz** [comment]
Great job iterating! This is really close now. 🌟 

### Bootstrap 3 vs 4

As we discussed IRL, the current stable version of Bootstrap is Bootstrap 3. Bootstrap 4 is out there as an alpha (early, unstable) version and will show up in your search results. You can tell when it's the Bootstrap 4 docs because the URL will include "v4-alpha." Even though Bootstrap 4 is so much easier and more powerful, we have to stick with Bootstrap 3 for any production projects (i.e., not stuff you're just playing around with on your own) so it will be stable and compatible with all browsers. 😿 

Check out the Bootstrap 3 navbar docs and make sure your navbar code works with Bootstrap 3 too, okay?
* * *
### Bootstrap grid system

So much better with this! 🎉 When you're using column classes, though, you don't need to specify if the element should be full width (`col-12`) on smaller sizes. That's already the default. You just need to provide a column class for any _breakpoints_ (where it will change). In this case, you want the `div`s to be 12 columns wide (the default) on `xs` and `sm` screens, then 6 columns wide on `md` and larger screens. So the only class you need to include is `col-md-6`. Does that make sense? It's a little hard for me to explain, for some reason. 😄 [These are the docs that show what I'm talking about](http://getbootstrap.com/css/#grid-example-basic).

#### Grid system bonus
Also, do you see how the left side of your page doesn't all line up? If you want it to line up, you could put _everything_ inside your `<div class="container">`. You might also need to put your `h1`, `h2`, and tagline inside row (and maybe even column) divs so they get the right padding too. This is optional, and I'm happy to help you figure it out if you want to play with it.

* * *
I'm literally right next to you if you have questions. 😆 But if you come back to this later, you can also reach me on Slack. Otherwise, comment when you're ready for another review! 🍪

**Comment by levinsonmm** [comment]
I believe I took care of the necessary changes, as we discussed that it was ok to keep the navbar as is. Let me know if there's anything else!

**Comment by KatieMFritz** [comment]
Great job! 🌈 ☁️ ✨ :shipit: 

For future reference, if an element in the Bootstrap 3 grid system should be full width on smaller screens, you don't have to include a `col-xs-12` class, `col-sm-12`, etc. Everything smaller than the breakpoint you specify (medium screens on this project, because of the `col-md-6` class) will automatically be 12 columns wide. 

One exception is if your content should ALWAYS be 12 columns wide, regardless of screen size. Then sometimes you need to specify a 12-column class (doesn't matter which size) so you get the right amount of margin/padding to line up with other widths of columns. Does that make sense? 🙂
